### ISSUE TITLE
Android is having issues with hash code occasionally

### ISSUE THREAD

**Issue by JayBeavers** [answer-als/companion#10]
Occasionally when uploading data, the Android app is sending with a hashcode of 'NoHashYet'.

![image](https://user-images.githubusercontent.com/1682199/60111054-1051f680-9722-11e9-88ca-42b02f2ceea7.png)

This is still happening on 1.6.

**Comment by cortensinger** [comment]
I have implemented a fix in this next coming update. As far as I can test on my end through the emulator, this hash issue seems to be fixed. But it would be good to have you test it again on your physical device
