### ISSUE TITLE
Please show sound loudness meter when recording

### ISSUE THREAD

**Issue by TeamGleasonDev** [answer-als/companion#5]
From Kely: Can we display sound wave so user knows if s/he is speaking to faint? I got cut mid sentences, got a message that signal was too low; then was presented the same image for a second try.

We discussed this today and we don't want to reject recordings or restart recordings because this can be discouraging and as the disease affects breathing it may be impossible for the person to speak loud enough.  Instead, let's show a real time meter that guides the user towards speaking 'in the green zone' (not too soft, not too loud) and accept/submit every recording.

**Comment by cortensinger** [comment]
I will remove the feature that stops the recording if the system detects no noise and will start implementing the "green zone" feature.
