### ISSUE TITLE
Soften the "no tasks available" message

### ISSUE THREAD

**Issue by TeamGleasonDev** [answer-als/companion#6]
From Kely:

after clicking done, was shown a message that no new task are open, that I need top check in a week. If there is only one task per week...and I just did it, what's the message about?

After discussing it, we decided that the 'no tasks available' message should be replaced with a friendly, "thank you for sending your data" message and then an app exit.

**Comment by knorel** [comment]
agree! fantastic. Thanks!
===============================================
Raquel (Kely) Norel, Ph.D.
rnorel@us.ibm.com
Computational Biology Center
IBM T.J. Watson Research Center

**Comment by cortensinger** [comment]
This sounds great. This will be done shortly :)
