### ISSUE TITLE
Consider visual accessibility - large fonts, high contrast, and landscape images

### ISSUE THREAD

**Issue by TeamGleasonDev** [answer-als/companion#7]
From Kely:

Some of the visual prompts are small (and most folks with ALS are 50+). Is it possible to enlarge the image? If not, can we increase the image contrast or background to help?

Please make a first pass at this.  Also, can you give me an idea of the cost of supporting landscape mode for image viewing?

**Comment by knorel** [comment]
I am not sure what is meant with enlarge the image....An option I see is to
rotate image
===============================================
Raquel (Kely) Norel, Ph.D.
rnorel@us.ibm.com
Computational Biology Center
IBM T.J. Watson Research Center
