### ISSUE TITLE
Add profile questions

### ISSUE THREAD

**Issue by TeamGleasonDev** [answer-als/companion#8]
From Kely:

Can we add handedness?
Date of symptom onset of (month and year)?
Can we add a question about diagnosis? Was it ALS, PLS, or some other neurological disease?
Can we add either question before if patient or control...or in "Describe your situation" one more box that says "control"

**Comment by knorel** [comment]
in particular we need handedness for when fine motors tasks will be added
(tapping/tracing)
let's make the initial profile as complete as possible, given that the idea
is later to allow people not in the study/trial to
use the app, so we will NOT have the profile data that clinical trial/study
manager is providing now
===============================================
Raquel (Kely) Norel, Ph.D.
rnorel@us.ibm.com
Computational Biology Center
IBM T.J. Watson Research Center

**Comment by cortensinger** [comment]
I can easily update Handedness - no problem.

I will also add a separate question at the beginning that asks whether the user is a Patient or a Control. If Control is selected, then the questionnaire will skip questions related to symptoms and diagnosis. If Patient is selected, then the questionnaire will ask users about Symptom Onset Site, Date of Symptom Onset, and a final question about the Diagnosis.

For the Diagnosis Question, Kely you provide the question "Was it ALS, PLS, or some other neurological disease?". In the app, I am thinking of framing the question using Radio Buttons like this...

'Please select the option that best describes your diagnosis:
o ALS
o PLS
o Other'

'If you selected Other, please briefly describe the diagnosis: _____________'

Does this sound good to you? Please let me know if youd like to see this implemented in a different way, thanks :)

**Comment by knorel** [comment]
>For the Diagnosis Question, Kely you provide the question "Was it ALS,
PLS, or some other neurological disease?". In the app, I am thinking of
framing the question using Radio Buttons like this...

It was not me....maybe Emily?

if you go with


'Please select the option that best describes your diagnosis:
o ALS
o PLS
o Other'





can u add a free txt to enter what other is?

===============================================
Raquel (Kely) Norel, Ph.D.
rnorel@us.ibm.com
Computational Biology Center
IBM T.J. Watson Research Center
