### ISSUE TITLE
Add 'pass' to tasks

### ISSUE THREAD

**Issue by TeamGleasonDev** [answer-als/companion#9]
From Kely:

If a participant cannot complete a task, can we include an option to “pass”?

**Comment by knorel** [comment]
we could include the option pass. What is the difference between pass and
just don't doing it? I guess, it let us know, it is not taht s/he forgot...
is just cannot do it that day/week.
Even if cannot complete....if we can record part of the task is more
information that saving none.
So: save as much data (voice for now, maybe tracing/tapping/etc in the
future)  as you can.
Kely
===============================================
Raquel (Kely) Norel, Ph.D.
rnorel@us.ibm.com
Computational Biology Center
IBM T.J. Watson Research Center

**Comment by cortensinger** [comment]
I can definitely add a Pass Button option. I have begun writing the code for this, but would love to hear your thoughts.

Currently, the Pass option will be a button on the Main page right next to the specific Task. Do we want this Pass option to upload info to the server that indicates a PASS? Do we want the app to wait a whole week before allowing the user to try the passed task again (same behavior as if it was completed normally)?

Also, if it is desired, I can update the instructions to remind users that they can try the tasks to the best of their ability and can submit the task even if not fully completed...currently the app does allow for this and it will upload whatever the user provides, but perhaps a stronger reminder will help?

**Comment by knorel** [comment]
Thanks Corten,
>I can definitely add a Pass Button option. I have begun writing the code
for this, but would love to hear your thoughts.
what's the difference between using the pass option of just not doing the
task? so we know s/he did not forgot to do the exercise?

>Also, if it is desired, I can update the instructions to remind users that
they can try the tasks to the best of their ability and can submit the task
even if not fully completed...currently the app does allow for this and it
will >upload whatever the user provides, but perhaps a stronger reminder
will help?

Yes, please! let's records as much as possible....even if partial task is
complete. A reminder to try your best is a good idea!
Cheers
Kely
===============================================
Raquel (Kely) Norel, Ph.D.
rnorel@us.ibm.com
Computational Biology Center
IBM T.J. Watson Research Center
